import path from 'path';

import type { ComponentDefinition } from './registry-utils';

export const components: ComponentDefinition[] = [
  {
    'name': 'hugeicons-a-arrow-down',
    'path': path.join(__dirname, '../icons/hugeicons/a-arrow-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-a-arrow-up',
    'path': path.join(__dirname, '../icons/hugeicons/a-arrow-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-air-vent',
    'path': path.join(__dirname, '../icons/hugeicons/air-vent.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-airplane-01',
    'path': path.join(__dirname, '../icons/hugeicons/airplane-01.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-airplay',
    'path': path.join(__dirname, '../icons/hugeicons/airplay.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-alarm-clock',
    'path': path.join(__dirname, '../icons/hugeicons/alarm-clock.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-alarm-clock-check',
    'path': path.join(__dirname, '../icons/hugeicons/alarm-clock-check.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-alarm-clock-minus',
    'path': path.join(__dirname, '../icons/hugeicons/alarm-clock-minus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-alarm-clock-plus',
    'path': path.join(__dirname, '../icons/hugeicons/alarm-clock-plus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-alarm-smoke',
    'path': path.join(__dirname, '../icons/hugeicons/alarm-smoke.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-align-horizontal-space-around',
    'path': path.join(
      __dirname,
      '../icons/hugeicons/align-horizontal-space-around.tsx'
    ),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-align-vertical-space-around',
    'path': path.join(
      __dirname,
      '../icons/hugeicons/align-vertical-space-around.tsx'
    ),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-ambulance',
    'path': path.join(__dirname, '../icons/hugeicons/ambulance.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-angry',
    'path': path.join(__dirname, '../icons/hugeicons/angry.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-annoyed',
    'path': path.join(__dirname, '../icons/hugeicons/annoyed.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-archive',
    'path': path.join(__dirname, '../icons/hugeicons/archive.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-big-down-dash',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-big-down-dash.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-big-left-dash',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-big-left-dash.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-big-right-dash',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-big-right-dash.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-big-up-dash',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-big-up-dash.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-down',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-down-az',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-down-az.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-down-big',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-down-big.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-down-left-01',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-down-left-01.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-down-one-zero',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-down-one-zero.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-down-right-01',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-down-right-01.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-down-za',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-down-za.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-down-zero-one',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-down-zero-one.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-left',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-left-big',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-left-big.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-right',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-right-big',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-right-big.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-up',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-up-big',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-up-big.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-up-left-01',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-up-left-01.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-up-right-01',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-up-right-01.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-at-sign',
    'path': path.join(__dirname, '../icons/hugeicons/at-sign.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-atom-02',
    'path': path.join(__dirname, '../icons/hugeicons/atom-02.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-attachment-01',
    'path': path.join(__dirname, '../icons/hugeicons/attachment-01.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-audio-lines',
    'path': path.join(__dirname, '../icons/hugeicons/audio-lines.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-axe',
    'path': path.join(__dirname, '../icons/hugeicons/axe.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-badge-alert',
    'path': path.join(__dirname, '../icons/hugeicons/badge-alert.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-badge-percent',
    'path': path.join(__dirname, '../icons/hugeicons/badge-percent.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-ban',
    'path': path.join(__dirname, '../icons/hugeicons/ban.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-banana',
    'path': path.join(__dirname, '../icons/hugeicons/banana.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-battery',
    'path': path.join(__dirname, '../icons/hugeicons/battery.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-battery-charging-02',
    'path': path.join(__dirname, '../icons/hugeicons/battery-charging-02.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-battery-full',
    'path': path.join(__dirname, '../icons/hugeicons/battery-full.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-battery-low',
    'path': path.join(__dirname, '../icons/hugeicons/battery-low.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-battery-medium-01',
    'path': path.join(__dirname, '../icons/hugeicons/battery-medium-01.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-battery-plus',
    'path': path.join(__dirname, '../icons/hugeicons/battery-plus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-battery-warning',
    'path': path.join(__dirname, '../icons/hugeicons/battery-warning.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-bell',
    'path': path.join(__dirname, '../icons/hugeicons/bell.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-bell-electric',
    'path': path.join(__dirname, '../icons/hugeicons/bell-electric.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-biceps-flexed',
    'path': path.join(__dirname, '../icons/hugeicons/biceps-flexed.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-binary',
    'path': path.join(__dirname, '../icons/hugeicons/binary.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-blocks',
    'path': path.join(__dirname, '../icons/hugeicons/blocks.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-bluetooth',
    'path': path.join(__dirname, '../icons/hugeicons/bluetooth.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-bluetooth-connected',
    'path': path.join(__dirname, '../icons/hugeicons/bluetooth-connected.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-bluetooth-off',
    'path': path.join(__dirname, '../icons/hugeicons/bluetooth-off.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-bluetooth-searching',
    'path': path.join(__dirname, '../icons/hugeicons/bluetooth-searching.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-bold',
    'path': path.join(__dirname, '../icons/hugeicons/bold.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-bone-01',
    'path': path.join(__dirname, '../icons/hugeicons/bone-01.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-book-text',
    'path': path.join(__dirname, '../icons/hugeicons/book-text.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-bookmark-01',
    'path': path.join(__dirname, '../icons/hugeicons/bookmark-01.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-bookmark-check-01',
    'path': path.join(__dirname, '../icons/hugeicons/bookmark-check-01.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-bookmark-minus-01',
    'path': path.join(__dirname, '../icons/hugeicons/bookmark-minus-01.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-bookmark-plus',
    'path': path.join(__dirname, '../icons/hugeicons/bookmark-plus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-bookmark-x',
    'path': path.join(__dirname, '../icons/hugeicons/bookmark-x.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-bot',
    'path': path.join(__dirname, '../icons/hugeicons/bot.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-bot-message-square',
    'path': path.join(__dirname, '../icons/hugeicons/bot-message-square.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-box',
    'path': path.join(__dirname, '../icons/hugeicons/box.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-boxes',
    'path': path.join(__dirname, '../icons/hugeicons/boxes.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-brain',
    'path': path.join(__dirname, '../icons/hugeicons/brain.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-briefcase-business',
    'path': path.join(__dirname, '../icons/hugeicons/briefcase-business.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-calendar',
    'path': path.join(__dirname, '../icons/hugeicons/calendar.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-calendar-check',
    'path': path.join(__dirname, '../icons/hugeicons/calendar-check.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-calendar-check-01',
    'path': path.join(__dirname, '../icons/hugeicons/calendar-check-01.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-calendar-cog',
    'path': path.join(__dirname, '../icons/hugeicons/calendar-cog.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-calendar-days',
    'path': path.join(__dirname, '../icons/hugeicons/calendar-days.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-cast',
    'path': path.join(__dirname, '../icons/hugeicons/cast.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-cctv-camera',
    'path': path.join(__dirname, '../icons/hugeicons/cctv-camera.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chart-bar-decreasing',
    'path': path.join(__dirname, '../icons/hugeicons/chart-bar-decreasing.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chart-bar-increasing',
    'path': path.join(__dirname, '../icons/hugeicons/chart-bar-increasing.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chart-column-decreasing',
    'path': path.join(
      __dirname,
      '../icons/hugeicons/chart-column-decreasing.tsx'
    ),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chart-column-increasing',
    'path': path.join(
      __dirname,
      '../icons/hugeicons/chart-column-increasing.tsx'
    ),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chart-line',
    'path': path.join(__dirname, '../icons/hugeicons/chart-line.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chart-no-axes-column-decreasing',
    'path': path.join(
      __dirname,
      '../icons/hugeicons/chart-no-axes-column-decreasing.tsx'
    ),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chart-no-axes-column-increasing',
    'path': path.join(
      __dirname,
      '../icons/hugeicons/chart-no-axes-column-increasing.tsx'
    ),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chart-scatter',
    'path': path.join(__dirname, '../icons/hugeicons/chart-scatter.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chart-spline',
    'path': path.join(__dirname, '../icons/hugeicons/chart-spline.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-check',
    'path': path.join(__dirname, '../icons/hugeicons/check.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-check-check',
    'path': path.join(__dirname, '../icons/hugeicons/check-check.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chess-bishop',
    'path': path.join(__dirname, '../icons/hugeicons/chess-bishop.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chess-king',
    'path': path.join(__dirname, '../icons/hugeicons/chess-king.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chess-knight',
    'path': path.join(__dirname, '../icons/hugeicons/chess-knight.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chess-pawn',
    'path': path.join(__dirname, '../icons/hugeicons/chess-pawn.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chevron-down',
    'path': path.join(__dirname, '../icons/hugeicons/chevron-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chevron-first',
    'path': path.join(__dirname, '../icons/hugeicons/chevron-first.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chevron-left',
    'path': path.join(__dirname, '../icons/hugeicons/chevron-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chevron-right',
    'path': path.join(__dirname, '../icons/hugeicons/chevron-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chevron-up',
    'path': path.join(__dirname, '../icons/hugeicons/chevron-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chevrons-down-up',
    'path': path.join(__dirname, '../icons/hugeicons/chevrons-down-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chevrons-left-right',
    'path': path.join(__dirname, '../icons/hugeicons/chevrons-left-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chevrons-right-left',
    'path': path.join(__dirname, '../icons/hugeicons/chevrons-right-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chrome',
    'path': path.join(__dirname, '../icons/hugeicons/chrome.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-cigarette',
    'path': path.join(__dirname, '../icons/hugeicons/cigarette.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-cigarette-off',
    'path': path.join(__dirname, '../icons/hugeicons/cigarette-off.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-circle-check',
    'path': path.join(__dirname, '../icons/hugeicons/circle-check.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-download',
    'path': path.join(__dirname, '../icons/hugeicons/download.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-eye',
    'path': path.join(__dirname, '../icons/hugeicons/eye.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-filter',
    'path': path.join(__dirname, '../icons/hugeicons/filter.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-heart',
    'path': path.join(__dirname, '../icons/hugeicons/heart.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-home',
    'path': path.join(__dirname, '../icons/hugeicons/home.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-lock',
    'path': path.join(__dirname, '../icons/hugeicons/lock.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-mail',
    'path': path.join(__dirname, '../icons/hugeicons/mail.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-menu',
    'path': path.join(__dirname, '../icons/hugeicons/menu.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-pencil',
    'path': path.join(__dirname, '../icons/hugeicons/pencil.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-pie-chart',
    'path': path.join(__dirname, '../icons/hugeicons/pie-chart.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-plus',
    'path': path.join(__dirname, '../icons/hugeicons/plus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-pulse-01',
    'path': path.join(__dirname, '../icons/hugeicons/pulse-01.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-refresh',
    'path': path.join(__dirname, '../icons/hugeicons/refresh.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-save',
    'path': path.join(__dirname, '../icons/hugeicons/save.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-search',
    'path': path.join(__dirname, '../icons/hugeicons/search.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-settings',
    'path': path.join(__dirname, '../icons/hugeicons/settings.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-share',
    'path': path.join(__dirname, '../icons/hugeicons/share.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-shopping-cart-01',
    'path': path.join(__dirname, '../icons/hugeicons/shopping-cart-01.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-star',
    'path': path.join(__dirname, '../icons/hugeicons/star.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-text-align-center',
    'path': path.join(__dirname, '../icons/hugeicons/text-align-center.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-text-align-left',
    'path': path.join(__dirname, '../icons/hugeicons/text-align-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-text-align-right',
    'path': path.join(__dirname, '../icons/hugeicons/text-align-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-trash',
    'path': path.join(__dirname, '../icons/hugeicons/trash.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-unfold-more',
    'path': path.join(__dirname, '../icons/hugeicons/unfold-more.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-universal-access',
    'path': path.join(__dirname, '../icons/hugeicons/universal-access.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-upload',
    'path': path.join(__dirname, '../icons/hugeicons/upload.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-user',
    'path': path.join(__dirname, '../icons/hugeicons/user.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-x',
    'path': path.join(__dirname, '../icons/hugeicons/x.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-airplane',
    'path': path.join(__dirname, '../icons/phosphor/airplane.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-airplay',
    'path': path.join(__dirname, '../icons/phosphor/airplay.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-alarm',
    'path': path.join(__dirname, '../icons/phosphor/alarm.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-align-center-horizontal',
    'path': path.join(
      __dirname,
      '../icons/phosphor/align-center-horizontal.tsx'
    ),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-align-center-vertical',
    'path': path.join(__dirname, '../icons/phosphor/align-center-vertical.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-ambulance',
    'path': path.join(__dirname, '../icons/phosphor/ambulance.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-archive',
    'path': path.join(__dirname, '../icons/phosphor/archive.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-down',
    'path': path.join(__dirname, '../icons/phosphor/arrow-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-down-left',
    'path': path.join(__dirname, '../icons/phosphor/arrow-down-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-down-right',
    'path': path.join(__dirname, '../icons/phosphor/arrow-down-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-fat-down',
    'path': path.join(__dirname, '../icons/phosphor/arrow-fat-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-fat-left',
    'path': path.join(__dirname, '../icons/phosphor/arrow-fat-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-fat-line-down',
    'path': path.join(__dirname, '../icons/phosphor/arrow-fat-line-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-fat-line-left',
    'path': path.join(__dirname, '../icons/phosphor/arrow-fat-line-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-fat-line-right',
    'path': path.join(__dirname, '../icons/phosphor/arrow-fat-line-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-fat-line-up',
    'path': path.join(__dirname, '../icons/phosphor/arrow-fat-line-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-fat-right',
    'path': path.join(__dirname, '../icons/phosphor/arrow-fat-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-fat-up',
    'path': path.join(__dirname, '../icons/phosphor/arrow-fat-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-left',
    'path': path.join(__dirname, '../icons/phosphor/arrow-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-right',
    'path': path.join(__dirname, '../icons/phosphor/arrow-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-up',
    'path': path.join(__dirname, '../icons/phosphor/arrow-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-up-left',
    'path': path.join(__dirname, '../icons/phosphor/arrow-up-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-up-right',
    'path': path.join(__dirname, '../icons/phosphor/arrow-up-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-at',
    'path': path.join(__dirname, '../icons/phosphor/at.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-atom',
    'path': path.join(__dirname, '../icons/phosphor/atom.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-axe',
    'path': path.join(__dirname, '../icons/phosphor/axe.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-battery-charging',
    'path': path.join(__dirname, '../icons/phosphor/battery-charging.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-battery-empty',
    'path': path.join(__dirname, '../icons/phosphor/battery-empty.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-battery-full',
    'path': path.join(__dirname, '../icons/phosphor/battery-full.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-battery-low',
    'path': path.join(__dirname, '../icons/phosphor/battery-low.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-battery-medium',
    'path': path.join(__dirname, '../icons/phosphor/battery-medium.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-battery-plus',
    'path': path.join(__dirname, '../icons/phosphor/battery-plus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-battery-warning',
    'path': path.join(__dirname, '../icons/phosphor/battery-warning.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-bell',
    'path': path.join(__dirname, '../icons/phosphor/bell.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-binary',
    'path': path.join(__dirname, '../icons/phosphor/binary.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-bluetooth',
    'path': path.join(__dirname, '../icons/phosphor/bluetooth.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-bluetooth-connected',
    'path': path.join(__dirname, '../icons/phosphor/bluetooth-connected.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-bluetooth-slash',
    'path': path.join(__dirname, '../icons/phosphor/bluetooth-slash.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-bone',
    'path': path.join(__dirname, '../icons/phosphor/bone.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-bookmark',
    'path': path.join(__dirname, '../icons/phosphor/bookmark.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-brain',
    'path': path.join(__dirname, '../icons/phosphor/brain.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-briefcase',
    'path': path.join(__dirname, '../icons/phosphor/briefcase.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-calendar',
    'path': path.join(__dirname, '../icons/phosphor/calendar.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-calendar-check',
    'path': path.join(__dirname, '../icons/phosphor/calendar-check.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-calendar-dots',
    'path': path.join(__dirname, '../icons/phosphor/calendar-dots.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-caret-line-left',
    'path': path.join(__dirname, '../icons/phosphor/caret-line-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-caret-up-down',
    'path': path.join(__dirname, '../icons/phosphor/caret-up-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-chart-bar',
    'path': path.join(__dirname, '../icons/phosphor/chart-bar.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-chart-line',
    'path': path.join(__dirname, '../icons/phosphor/chart-line.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-chart-pie',
    'path': path.join(__dirname, '../icons/phosphor/chart-pie.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-chart-scatter',
    'path': path.join(__dirname, '../icons/phosphor/chart-scatter.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-check',
    'path': path.join(__dirname, '../icons/phosphor/check.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-check-circle',
    'path': path.join(__dirname, '../icons/phosphor/check-circle.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-checks',
    'path': path.join(__dirname, '../icons/phosphor/checks.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-chevron-down',
    'path': path.join(__dirname, '../icons/phosphor/chevron-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-chevron-left',
    'path': path.join(__dirname, '../icons/phosphor/chevron-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-chevron-right',
    'path': path.join(__dirname, '../icons/phosphor/chevron-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-chevron-up',
    'path': path.join(__dirname, '../icons/phosphor/chevron-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-cigarette',
    'path': path.join(__dirname, '../icons/phosphor/cigarette.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-cigarette-slash',
    'path': path.join(__dirname, '../icons/phosphor/cigarette-slash.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-cube',
    'path': path.join(__dirname, '../icons/phosphor/cube.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-download',
    'path': path.join(__dirname, '../icons/phosphor/download.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-envelope',
    'path': path.join(__dirname, '../icons/phosphor/envelope.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-eye',
    'path': path.join(__dirname, '../icons/phosphor/eye.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-filter',
    'path': path.join(__dirname, '../icons/phosphor/filter.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-gear',
    'path': path.join(__dirname, '../icons/phosphor/gear.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-google-chrome-logo',
    'path': path.join(__dirname, '../icons/phosphor/google-chrome-logo.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-heart',
    'path': path.join(__dirname, '../icons/phosphor/heart.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-house',
    'path': path.join(__dirname, '../icons/phosphor/house.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-list',
    'path': path.join(__dirname, '../icons/phosphor/list.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-lock',
    'path': path.join(__dirname, '../icons/phosphor/lock.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-notebook',
    'path': path.join(__dirname, '../icons/phosphor/notebook.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-paperclip',
    'path': path.join(__dirname, '../icons/phosphor/paperclip.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-pencil',
    'path': path.join(__dirname, '../icons/phosphor/pencil.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-person-arms-spread',
    'path': path.join(__dirname, '../icons/phosphor/person-arms-spread.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-plus',
    'path': path.join(__dirname, '../icons/phosphor/plus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-prohibit',
    'path': path.join(__dirname, '../icons/phosphor/prohibit.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-pulse',
    'path': path.join(__dirname, '../icons/phosphor/pulse.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-refresh',
    'path': path.join(__dirname, '../icons/phosphor/refresh.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-robot',
    'path': path.join(__dirname, '../icons/phosphor/robot.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-save',
    'path': path.join(__dirname, '../icons/phosphor/save.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-screencast',
    'path': path.join(__dirname, '../icons/phosphor/screencast.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-seal-percent',
    'path': path.join(__dirname, '../icons/phosphor/seal-percent.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-seal-warning',
    'path': path.join(__dirname, '../icons/phosphor/seal-warning.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-search',
    'path': path.join(__dirname, '../icons/phosphor/search.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-security-camera',
    'path': path.join(__dirname, '../icons/phosphor/security-camera.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-share',
    'path': path.join(__dirname, '../icons/phosphor/share.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-shopping-cart',
    'path': path.join(__dirname, '../icons/phosphor/shopping-cart.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-smiley-angry',
    'path': path.join(__dirname, '../icons/phosphor/smiley-angry.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-smiley-meh',
    'path': path.join(__dirname, '../icons/phosphor/smiley-meh.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-sort-ascending',
    'path': path.join(__dirname, '../icons/phosphor/sort-ascending.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-sort-descending',
    'path': path.join(__dirname, '../icons/phosphor/sort-descending.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-star',
    'path': path.join(__dirname, '../icons/phosphor/star.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-text-align-center',
    'path': path.join(__dirname, '../icons/phosphor/text-align-center.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-text-align-left',
    'path': path.join(__dirname, '../icons/phosphor/text-align-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-text-align-right',
    'path': path.join(__dirname, '../icons/phosphor/text-align-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-text-b',
    'path': path.join(__dirname, '../icons/phosphor/text-b.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-trash',
    'path': path.join(__dirname, '../icons/phosphor/trash.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-upload',
    'path': path.join(__dirname, '../icons/phosphor/upload.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-user',
    'path': path.join(__dirname, '../icons/phosphor/user.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-waveform',
    'path': path.join(__dirname, '../icons/phosphor/waveform.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-x',
    'path': path.join(__dirname, '../icons/phosphor/x.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-accessible',
    'path': path.join(__dirname, '../icons/tabler/accessible.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-activity',
    'path': path.join(__dirname, '../icons/tabler/activity.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-air-conditioning',
    'path': path.join(__dirname, '../icons/tabler/air-conditioning.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-alarm',
    'path': path.join(__dirname, '../icons/tabler/alarm.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-alarm-minus',
    'path': path.join(__dirname, '../icons/tabler/alarm-minus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-alarm-plus',
    'path': path.join(__dirname, '../icons/tabler/alarm-plus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-alarm-smoke',
    'path': path.join(__dirname, '../icons/tabler/alarm-smoke.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-align-center',
    'path': path.join(__dirname, '../icons/tabler/align-center.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-align-left',
    'path': path.join(__dirname, '../icons/tabler/align-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-align-right',
    'path': path.join(__dirname, '../icons/tabler/align-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-ambulance',
    'path': path.join(__dirname, '../icons/tabler/ambulance.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-archive',
    'path': path.join(__dirname, '../icons/tabler/archive.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-big-down',
    'path': path.join(__dirname, '../icons/tabler/arrow-big-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-big-down-line',
    'path': path.join(__dirname, '../icons/tabler/arrow-big-down-line.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-big-left',
    'path': path.join(__dirname, '../icons/tabler/arrow-big-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-big-left-line',
    'path': path.join(__dirname, '../icons/tabler/arrow-big-left-line.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-big-right',
    'path': path.join(__dirname, '../icons/tabler/arrow-big-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-big-right-line',
    'path': path.join(__dirname, '../icons/tabler/arrow-big-right-line.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-big-up',
    'path': path.join(__dirname, '../icons/tabler/arrow-big-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-big-up-line',
    'path': path.join(__dirname, '../icons/tabler/arrow-big-up-line.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-down',
    'path': path.join(__dirname, '../icons/tabler/arrow-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-down-left',
    'path': path.join(__dirname, '../icons/tabler/arrow-down-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-down-right',
    'path': path.join(__dirname, '../icons/tabler/arrow-down-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-left',
    'path': path.join(__dirname, '../icons/tabler/arrow-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-right',
    'path': path.join(__dirname, '../icons/tabler/arrow-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-up',
    'path': path.join(__dirname, '../icons/tabler/arrow-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-up-left',
    'path': path.join(__dirname, '../icons/tabler/arrow-up-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-up-right',
    'path': path.join(__dirname, '../icons/tabler/arrow-up-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-at',
    'path': path.join(__dirname, '../icons/tabler/at.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-atom',
    'path': path.join(__dirname, '../icons/tabler/atom.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-axe',
    'path': path.join(__dirname, '../icons/tabler/axe.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-ban',
    'path': path.join(__dirname, '../icons/tabler/ban.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-banana',
    'path': path.join(__dirname, '../icons/tabler/banana.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-battery',
    'path': path.join(__dirname, '../icons/tabler/battery.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-battery-1',
    'path': path.join(__dirname, '../icons/tabler/battery-1.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-battery-2',
    'path': path.join(__dirname, '../icons/tabler/battery-2.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-battery-4',
    'path': path.join(__dirname, '../icons/tabler/battery-4.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-battery-charging',
    'path': path.join(__dirname, '../icons/tabler/battery-charging.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-battery-exclamation',
    'path': path.join(__dirname, '../icons/tabler/battery-exclamation.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-bell',
    'path': path.join(__dirname, '../icons/tabler/bell.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-bell-school',
    'path': path.join(__dirname, '../icons/tabler/bell-school.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-binary',
    'path': path.join(__dirname, '../icons/tabler/binary.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-blocks',
    'path': path.join(__dirname, '../icons/tabler/blocks.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-bluetooth',
    'path': path.join(__dirname, '../icons/tabler/bluetooth.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-bluetooth-connected',
    'path': path.join(__dirname, '../icons/tabler/bluetooth-connected.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-bluetooth-off',
    'path': path.join(__dirname, '../icons/tabler/bluetooth-off.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-bold',
    'path': path.join(__dirname, '../icons/tabler/bold.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-bone',
    'path': path.join(__dirname, '../icons/tabler/bone.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-book-2',
    'path': path.join(__dirname, '../icons/tabler/book-2.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-bookmark',
    'path': path.join(__dirname, '../icons/tabler/bookmark.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-bookmark-minus',
    'path': path.join(__dirname, '../icons/tabler/bookmark-minus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-bookmark-plus',
    'path': path.join(__dirname, '../icons/tabler/bookmark-plus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-box',
    'path': path.join(__dirname, '../icons/tabler/box.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-brain',
    'path': path.join(__dirname, '../icons/tabler/brain.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-brand-chrome',
    'path': path.join(__dirname, '../icons/tabler/brand-chrome.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-briefcase',
    'path': path.join(__dirname, '../icons/tabler/briefcase.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-calendar',
    'path': path.join(__dirname, '../icons/tabler/calendar.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-calendar-check',
    'path': path.join(__dirname, '../icons/tabler/calendar-check.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-calendar-cog',
    'path': path.join(__dirname, '../icons/tabler/calendar-cog.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-calendar-week',
    'path': path.join(__dirname, '../icons/tabler/calendar-week.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-cast',
    'path': path.join(__dirname, '../icons/tabler/cast.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chart-bar-popular',
    'path': path.join(__dirname, '../icons/tabler/chart-bar-popular.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chart-line',
    'path': path.join(__dirname, '../icons/tabler/chart-line.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chart-pie',
    'path': path.join(__dirname, '../icons/tabler/chart-pie.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chart-scatter',
    'path': path.join(__dirname, '../icons/tabler/chart-scatter.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-check',
    'path': path.join(__dirname, '../icons/tabler/check.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-checks',
    'path': path.join(__dirname, '../icons/tabler/checks.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chess',
    'path': path.join(__dirname, '../icons/tabler/chess.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chess-bishop',
    'path': path.join(__dirname, '../icons/tabler/chess-bishop.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chess-king',
    'path': path.join(__dirname, '../icons/tabler/chess-king.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chess-knight',
    'path': path.join(__dirname, '../icons/tabler/chess-knight.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chevron-down',
    'path': path.join(__dirname, '../icons/tabler/chevron-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chevron-left',
    'path': path.join(__dirname, '../icons/tabler/chevron-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chevron-left-pipe',
    'path': path.join(__dirname, '../icons/tabler/chevron-left-pipe.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chevron-right',
    'path': path.join(__dirname, '../icons/tabler/chevron-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chevron-up',
    'path': path.join(__dirname, '../icons/tabler/chevron-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-circle-check',
    'path': path.join(__dirname, '../icons/tabler/circle-check.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-device-cctv',
    'path': path.join(__dirname, '../icons/tabler/device-cctv.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-download',
    'path': path.join(__dirname, '../icons/tabler/download.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-eye',
    'path': path.join(__dirname, '../icons/tabler/eye.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-filter',
    'path': path.join(__dirname, '../icons/tabler/filter.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-heart',
    'path': path.join(__dirname, '../icons/tabler/heart.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-home',
    'path': path.join(__dirname, '../icons/tabler/home.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-layout-align-center',
    'path': path.join(__dirname, '../icons/tabler/layout-align-center.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-layout-align-middle',
    'path': path.join(__dirname, '../icons/tabler/layout-align-middle.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-lock',
    'path': path.join(__dirname, '../icons/tabler/lock.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-mail',
    'path': path.join(__dirname, '../icons/tabler/mail.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-menu',
    'path': path.join(__dirname, '../icons/tabler/menu.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-message-chatbot',
    'path': path.join(__dirname, '../icons/tabler/message-chatbot.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-mood-angry',
    'path': path.join(__dirname, '../icons/tabler/mood-angry.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-mood-annoyed',
    'path': path.join(__dirname, '../icons/tabler/mood-annoyed.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-packages',
    'path': path.join(__dirname, '../icons/tabler/packages.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-paperclip',
    'path': path.join(__dirname, '../icons/tabler/paperclip.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-pencil',
    'path': path.join(__dirname, '../icons/tabler/pencil.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-plane',
    'path': path.join(__dirname, '../icons/tabler/plane.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-plus',
    'path': path.join(__dirname, '../icons/tabler/plus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-refresh',
    'path': path.join(__dirname, '../icons/tabler/refresh.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-robot',
    'path': path.join(__dirname, '../icons/tabler/robot.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-rosette-discount',
    'path': path.join(__dirname, '../icons/tabler/rosette-discount.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-save',
    'path': path.join(__dirname, '../icons/tabler/save.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-search',
    'path': path.join(__dirname, '../icons/tabler/search.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-selector',
    'path': path.join(__dirname, '../icons/tabler/selector.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-settings',
    'path': path.join(__dirname, '../icons/tabler/settings.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-share',
    'path': path.join(__dirname, '../icons/tabler/share.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-shopping-cart',
    'path': path.join(__dirname, '../icons/tabler/shopping-cart.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-smoking',
    'path': path.join(__dirname, '../icons/tabler/smoking.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-smoking-no',
    'path': path.join(__dirname, '../icons/tabler/smoking-no.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-sort-ascending-letters',
    'path': path.join(__dirname, '../icons/tabler/sort-ascending-letters.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-sort-ascending-numbers',
    'path': path.join(__dirname, '../icons/tabler/sort-ascending-numbers.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-sort-descending-letters',
    'path': path.join(__dirname, '../icons/tabler/sort-descending-letters.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-sort-descending-numbers',
    'path': path.join(__dirname, '../icons/tabler/sort-descending-numbers.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-star',
    'path': path.join(__dirname, '../icons/tabler/star.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-trash',
    'path': path.join(__dirname, '../icons/tabler/trash.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-upload',
    'path': path.join(__dirname, '../icons/tabler/upload.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-user',
    'path': path.join(__dirname, '../icons/tabler/user.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-x',
    'path': path.join(__dirname, '../icons/tabler/x.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
];
