import path from 'path';

import type { ComponentDefinition } from './registry-utils';

export const components: ComponentDefinition[] = [
  {
    'name': 'hugeicons-a-arrow-down',
    'path': path.join(__dirname, '../icons/hugeicons/a-arrow-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-a-arrow-up',
    'path': path.join(__dirname, '../icons/hugeicons/a-arrow-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-air-vent',
    'path': path.join(__dirname, '../icons/hugeicons/air-vent.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-airplane-01',
    'path': path.join(__dirname, '../icons/hugeicons/airplane-01.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-airplay',
    'path': path.join(__dirname, '../icons/hugeicons/airplay.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-alarm-clock',
    'path': path.join(__dirname, '../icons/hugeicons/alarm-clock.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-alarm-clock-check',
    'path': path.join(__dirname, '../icons/hugeicons/alarm-clock-check.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-alarm-clock-minus',
    'path': path.join(__dirname, '../icons/hugeicons/alarm-clock-minus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-alarm-clock-plus',
    'path': path.join(__dirname, '../icons/hugeicons/alarm-clock-plus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-alarm-smoke',
    'path': path.join(__dirname, '../icons/hugeicons/alarm-smoke.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-align-horizontal-space-around',
    'path': path.join(
      __dirname,
      '../icons/hugeicons/align-horizontal-space-around.tsx'
    ),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-align-vertical-space-around',
    'path': path.join(
      __dirname,
      '../icons/hugeicons/align-vertical-space-around.tsx'
    ),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-ambulance',
    'path': path.join(__dirname, '../icons/hugeicons/ambulance.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-angry',
    'path': path.join(__dirname, '../icons/hugeicons/angry.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-annoyed',
    'path': path.join(__dirname, '../icons/hugeicons/annoyed.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-archive',
    'path': path.join(__dirname, '../icons/hugeicons/archive.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-big-down-dash',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-big-down-dash.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-big-left-dash',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-big-left-dash.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-down',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-down-big',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-down-big.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-left',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-left-big',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-left-big.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-right',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-arrow-up',
    'path': path.join(__dirname, '../icons/hugeicons/arrow-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-bell',
    'path': path.join(__dirname, '../icons/hugeicons/bell.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-calendar',
    'path': path.join(__dirname, '../icons/hugeicons/calendar.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-check',
    'path': path.join(__dirname, '../icons/hugeicons/check.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chevron-down',
    'path': path.join(__dirname, '../icons/hugeicons/chevron-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chevron-left',
    'path': path.join(__dirname, '../icons/hugeicons/chevron-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chevron-right',
    'path': path.join(__dirname, '../icons/hugeicons/chevron-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-chevron-up',
    'path': path.join(__dirname, '../icons/hugeicons/chevron-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-download',
    'path': path.join(__dirname, '../icons/hugeicons/download.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-eye',
    'path': path.join(__dirname, '../icons/hugeicons/eye.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-filter',
    'path': path.join(__dirname, '../icons/hugeicons/filter.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-heart',
    'path': path.join(__dirname, '../icons/hugeicons/heart.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-home',
    'path': path.join(__dirname, '../icons/hugeicons/home.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-lock',
    'path': path.join(__dirname, '../icons/hugeicons/lock.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-mail',
    'path': path.join(__dirname, '../icons/hugeicons/mail.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-menu',
    'path': path.join(__dirname, '../icons/hugeicons/menu.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-pencil',
    'path': path.join(__dirname, '../icons/hugeicons/pencil.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-plus',
    'path': path.join(__dirname, '../icons/hugeicons/plus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-pulse-01',
    'path': path.join(__dirname, '../icons/hugeicons/pulse-01.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-refresh',
    'path': path.join(__dirname, '../icons/hugeicons/refresh.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-save',
    'path': path.join(__dirname, '../icons/hugeicons/save.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-search',
    'path': path.join(__dirname, '../icons/hugeicons/search.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-settings',
    'path': path.join(__dirname, '../icons/hugeicons/settings.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-share',
    'path': path.join(__dirname, '../icons/hugeicons/share.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-star',
    'path': path.join(__dirname, '../icons/hugeicons/star.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-text-align-center',
    'path': path.join(__dirname, '../icons/hugeicons/text-align-center.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-text-align-left',
    'path': path.join(__dirname, '../icons/hugeicons/text-align-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-text-align-right',
    'path': path.join(__dirname, '../icons/hugeicons/text-align-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-trash',
    'path': path.join(__dirname, '../icons/hugeicons/trash.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-universal-access',
    'path': path.join(__dirname, '../icons/hugeicons/universal-access.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-upload',
    'path': path.join(__dirname, '../icons/hugeicons/upload.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-user',
    'path': path.join(__dirname, '../icons/hugeicons/user.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'hugeicons-x',
    'path': path.join(__dirname, '../icons/hugeicons/x.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-airplane',
    'path': path.join(__dirname, '../icons/phosphor/airplane.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-airplay',
    'path': path.join(__dirname, '../icons/phosphor/airplay.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-alarm',
    'path': path.join(__dirname, '../icons/phosphor/alarm.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-align-center-horizontal',
    'path': path.join(
      __dirname,
      '../icons/phosphor/align-center-horizontal.tsx'
    ),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-align-center-vertical',
    'path': path.join(__dirname, '../icons/phosphor/align-center-vertical.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-ambulance',
    'path': path.join(__dirname, '../icons/phosphor/ambulance.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-archive',
    'path': path.join(__dirname, '../icons/phosphor/archive.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-down',
    'path': path.join(__dirname, '../icons/phosphor/arrow-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-fat-down',
    'path': path.join(__dirname, '../icons/phosphor/arrow-fat-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-fat-left',
    'path': path.join(__dirname, '../icons/phosphor/arrow-fat-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-fat-line-down',
    'path': path.join(__dirname, '../icons/phosphor/arrow-fat-line-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-fat-line-left',
    'path': path.join(__dirname, '../icons/phosphor/arrow-fat-line-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-left',
    'path': path.join(__dirname, '../icons/phosphor/arrow-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-right',
    'path': path.join(__dirname, '../icons/phosphor/arrow-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-arrow-up',
    'path': path.join(__dirname, '../icons/phosphor/arrow-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-bell',
    'path': path.join(__dirname, '../icons/phosphor/bell.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-calendar',
    'path': path.join(__dirname, '../icons/phosphor/calendar.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-check',
    'path': path.join(__dirname, '../icons/phosphor/check.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-chevron-down',
    'path': path.join(__dirname, '../icons/phosphor/chevron-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-chevron-left',
    'path': path.join(__dirname, '../icons/phosphor/chevron-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-chevron-right',
    'path': path.join(__dirname, '../icons/phosphor/chevron-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-chevron-up',
    'path': path.join(__dirname, '../icons/phosphor/chevron-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-download',
    'path': path.join(__dirname, '../icons/phosphor/download.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-envelope',
    'path': path.join(__dirname, '../icons/phosphor/envelope.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-eye',
    'path': path.join(__dirname, '../icons/phosphor/eye.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-filter',
    'path': path.join(__dirname, '../icons/phosphor/filter.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-gear',
    'path': path.join(__dirname, '../icons/phosphor/gear.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-heart',
    'path': path.join(__dirname, '../icons/phosphor/heart.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-house',
    'path': path.join(__dirname, '../icons/phosphor/house.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-list',
    'path': path.join(__dirname, '../icons/phosphor/list.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-lock',
    'path': path.join(__dirname, '../icons/phosphor/lock.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-pencil',
    'path': path.join(__dirname, '../icons/phosphor/pencil.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-person-arms-spread',
    'path': path.join(__dirname, '../icons/phosphor/person-arms-spread.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-plus',
    'path': path.join(__dirname, '../icons/phosphor/plus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-pulse',
    'path': path.join(__dirname, '../icons/phosphor/pulse.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-refresh',
    'path': path.join(__dirname, '../icons/phosphor/refresh.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-save',
    'path': path.join(__dirname, '../icons/phosphor/save.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-search',
    'path': path.join(__dirname, '../icons/phosphor/search.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-share',
    'path': path.join(__dirname, '../icons/phosphor/share.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-smiley-angry',
    'path': path.join(__dirname, '../icons/phosphor/smiley-angry.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-smiley-meh',
    'path': path.join(__dirname, '../icons/phosphor/smiley-meh.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-star',
    'path': path.join(__dirname, '../icons/phosphor/star.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-text-align-center',
    'path': path.join(__dirname, '../icons/phosphor/text-align-center.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-text-align-left',
    'path': path.join(__dirname, '../icons/phosphor/text-align-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-text-align-right',
    'path': path.join(__dirname, '../icons/phosphor/text-align-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-trash',
    'path': path.join(__dirname, '../icons/phosphor/trash.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-upload',
    'path': path.join(__dirname, '../icons/phosphor/upload.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-user',
    'path': path.join(__dirname, '../icons/phosphor/user.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'phosphor-x',
    'path': path.join(__dirname, '../icons/phosphor/x.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-accessible',
    'path': path.join(__dirname, '../icons/tabler/accessible.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-activity',
    'path': path.join(__dirname, '../icons/tabler/activity.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-air-conditioning',
    'path': path.join(__dirname, '../icons/tabler/air-conditioning.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-alarm',
    'path': path.join(__dirname, '../icons/tabler/alarm.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-alarm-minus',
    'path': path.join(__dirname, '../icons/tabler/alarm-minus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-alarm-plus',
    'path': path.join(__dirname, '../icons/tabler/alarm-plus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-alarm-smoke',
    'path': path.join(__dirname, '../icons/tabler/alarm-smoke.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-align-center',
    'path': path.join(__dirname, '../icons/tabler/align-center.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-align-left',
    'path': path.join(__dirname, '../icons/tabler/align-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-align-right',
    'path': path.join(__dirname, '../icons/tabler/align-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-ambulance',
    'path': path.join(__dirname, '../icons/tabler/ambulance.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-archive',
    'path': path.join(__dirname, '../icons/tabler/archive.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-big-down',
    'path': path.join(__dirname, '../icons/tabler/arrow-big-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-big-down-line',
    'path': path.join(__dirname, '../icons/tabler/arrow-big-down-line.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-big-left',
    'path': path.join(__dirname, '../icons/tabler/arrow-big-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-big-left-line',
    'path': path.join(__dirname, '../icons/tabler/arrow-big-left-line.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-down',
    'path': path.join(__dirname, '../icons/tabler/arrow-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-left',
    'path': path.join(__dirname, '../icons/tabler/arrow-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-right',
    'path': path.join(__dirname, '../icons/tabler/arrow-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-arrow-up',
    'path': path.join(__dirname, '../icons/tabler/arrow-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-bell',
    'path': path.join(__dirname, '../icons/tabler/bell.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-calendar',
    'path': path.join(__dirname, '../icons/tabler/calendar.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-check',
    'path': path.join(__dirname, '../icons/tabler/check.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chevron-down',
    'path': path.join(__dirname, '../icons/tabler/chevron-down.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chevron-left',
    'path': path.join(__dirname, '../icons/tabler/chevron-left.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chevron-right',
    'path': path.join(__dirname, '../icons/tabler/chevron-right.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-chevron-up',
    'path': path.join(__dirname, '../icons/tabler/chevron-up.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-download',
    'path': path.join(__dirname, '../icons/tabler/download.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-eye',
    'path': path.join(__dirname, '../icons/tabler/eye.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-filter',
    'path': path.join(__dirname, '../icons/tabler/filter.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-heart',
    'path': path.join(__dirname, '../icons/tabler/heart.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-home',
    'path': path.join(__dirname, '../icons/tabler/home.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-layout-align-center',
    'path': path.join(__dirname, '../icons/tabler/layout-align-center.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-layout-align-middle',
    'path': path.join(__dirname, '../icons/tabler/layout-align-middle.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-lock',
    'path': path.join(__dirname, '../icons/tabler/lock.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-mail',
    'path': path.join(__dirname, '../icons/tabler/mail.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-menu',
    'path': path.join(__dirname, '../icons/tabler/menu.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-mood-angry',
    'path': path.join(__dirname, '../icons/tabler/mood-angry.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-mood-annoyed',
    'path': path.join(__dirname, '../icons/tabler/mood-annoyed.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-pencil',
    'path': path.join(__dirname, '../icons/tabler/pencil.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-plane',
    'path': path.join(__dirname, '../icons/tabler/plane.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-plus',
    'path': path.join(__dirname, '../icons/tabler/plus.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-refresh',
    'path': path.join(__dirname, '../icons/tabler/refresh.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-save',
    'path': path.join(__dirname, '../icons/tabler/save.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-search',
    'path': path.join(__dirname, '../icons/tabler/search.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-settings',
    'path': path.join(__dirname, '../icons/tabler/settings.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-share',
    'path': path.join(__dirname, '../icons/tabler/share.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-star',
    'path': path.join(__dirname, '../icons/tabler/star.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-trash',
    'path': path.join(__dirname, '../icons/tabler/trash.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-upload',
    'path': path.join(__dirname, '../icons/tabler/upload.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-user',
    'path': path.join(__dirname, '../icons/tabler/user.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
  {
    'name': 'tabler-x',
    'path': path.join(__dirname, '../icons/tabler/x.tsx'),
    'registryDependencies': [],
    'dependencies': ['motion'],
  },
];
